/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IAaveAcl, IAaveAclInterface } from "../IAaveAcl";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "admin",
        type: "address",
      },
    ],
    name: "addPoolAdmin",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "admin",
        type: "address",
      },
    ],
    name: "isPoolAdmin",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IAaveAcl__factory {
  static readonly abi = _abi;
  static createInterface(): IAaveAclInterface {
    return new utils.Interface(_abi) as IAaveAclInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAaveAcl {
    return new Contract(address, _abi, signerOrProvider) as IAaveAcl;
  }
}
